# Background {#background}

## Archaeological context: British Neolithic axes

The history of stone implement study in archaeology had a turning point in the 1920s, up until which a so-called collector’s approach had been dominant, which asserted that the preservation, appearance and integrity of axes were important above all else [@grimes1935 424]. This meant that typologies were built predominantly upon appearance. In this decade, a move away from this school of thought was spurred on by such studies as that of Thomas, a geologist who inspected characteristic inclusions in the stonehenge ‘foreign’ blue stones and found the same pattern in boulders in Pembrokeshire, Wales and followed them into the Prescelly Mountains, where more of this type of rock was found *in situ* [@thomas1923 247, 248]. These stonehenge stones were called foreign as until provenancing became mainstream, axes and other stone artefacts found in areas with no clear stone source were given this name [@grimes1979 1]. Thomas was part of the British Geological Survey, started at the beginning of the 1900s to catalogue stone types in Britain, which would later be useful for further provenancing of stone implements. Another important development was that archaeologists in 1930s southern England began taking thin sections of axes to analyse, which kept the structural integrity of the axe but allowed the study of internal inclusions with a microscope [@grimes1979 1]. This technique was used by the Sub-Committee of the South-Western Group of Museums and Art Galleries on the Petrological Identification of Stone Axes, formed in 1936, which also named the first set of petrological groups, and eventually published a petrological report of more than 200 specimens. The main aim of the South-West Committee was essentially to analyse the petrography of stone artefacts, normally tools, collate previous work and publish the results [@keiller1937 485]. Their first report in 1941 asserts that a previous hindrance in the study of stone artefacts was that their owners forbade any modification, however minute, which meant that petrologists were expected to identify the type of stone just from the surface. Due to the nature of axe manufacture, this was impractical, as much of the surface would have been worn away by grinding, polishing and so on [@keiller1941 50]. This publication further cemented the idea that artefacts were no longer just pieces in a display cabinet but specimens for scientific investigation. Later, the South-West Committee’s records were integrated with those from the rest of England and the national survey was created, the central committee of which became the Implement Petrology Committee. The Committee was responsible for publishing the largest stone implement survey so far, Stone Axe Studies ii, recording the petrology of 7625 axes, which ranged in period from the early Neolithic to the Bronze Age. This exhaustive survey covered all of the UK, with the largest number coming from south-west England [@clough1988 3]. Important provenancing information was discovered and recorded for an unprecedented amount of artefacts in this survey, forming the basis for future research on production and exchange of these items, a topic that is once again prominent in the current literature. Later, the Implement Petrology Committee would become the Implement Petrology Group, which still exists today, and whose members were responsible for scanning the dataset used in this paper.

Shortly after its publication, however, reviews of Stone Axe Studies ii expressed disappointment that the volume mainly reported the results of petrological analyses, and did not attempt to address such contentious topics as the distinction between petrological groups, or what may have led to the dispersal of these artefacts at such distances from their sources, and in such close proximity to other raw materials [@edmonds1989 633]. However, it its defense, Stone Axe Studies ii did exactly what it set out to do: catalogue the provenances of as many stone axes as possible. Mike Pitts, the author of the dataset in this dissertation, cited such reviews in his 1996 paper as he too thought that the 1988 IPC volume left more to be desired. He states that because of the heavy focus on finding the origin of stone implements for the past few decades, there had been little interest in methods of manufacture, potential differing functions, or emergent styles of stone implements. Pitts also points out that there was often disagreement between petrologists on which stone group an axe belonged to, highlighting the subjective nature of previous categorisation methods [@pitts1996 311]. His paper included PCA, k-means and linear discriminant analysis on the measurements in the axe dataset he compiled, in addition to creating six much broader axe groups (p313). There had been forays into similar morphometric analyses of stone tools in the past, however not from the Neolithic [@roe1969 23].

In recent years, Neolithic axes have received renewed attention, with investigations ranging from those concerning their potential meanings to those investigating why they were dispersed or manufactured in the way that they were. Stone Axe Studies III, the latest volume of the IPC’s series, presented the latest findings about stone implement artefacts at home and abroad, with a number of the British articles concerning Neolithic axes. Within this volume, an article of a more speculative nature focuses on the meaning of the axes to Neolithic people. Examples include Darvill (p140) who suggests that the stone chosen for axe manufacture may have had symbolic significance, and Clarke (p319) who observes that Neolithic axes in Orkney tended to differ in size depending on the context they were found in, with larger, more complete specimens being found in graves [@darvill2011 140; @clarke2011 319]. A significant study is that by Walker, who posited that axe heads imported by incoming immigrant populations from continental Europe had influence on axe design in Neolithic Britain, and resulted in copying [@walker2015 105]. She additionally suggests that the difficult-to-reach nature of many quarry sites in Britain could be part of the reason why these locations were chosen, perhaps as a form of pilgrimage or rite of passage [@walker2015 233]. In addition to these discussions considering the structure and function of Neolithic axes in Britain, radiocarbon dating was being used increasingly in conjunction with provenance data in order to ascertain how tool use, manufacture and demography changed over time, and whether they were linked. One such example is the NEOMINE project undertaken by Shennan *et al.*, who were able to ascertain that mining activity in Britain coincided with a period of forest clearing that preceeded the introduction of farming by approximately 200 years [@shennan2017 78]. The main impetus of this project was to collect radiocarbon dates for all of Britain’s Neolithic mines. The authors also suggest that Neolithic populations from the continent immigrated to Britain and brought farming techniques with them, beginning to mine and clearing forests beforehand. In Scotland, it is also known that elm and birch pollen percentages rapidly declined in the Beinn Lawers palaeoenvironmental record around 3350 cal BC, which coincided with the uptake of stone axe manufacture at Creag na Caillich [@tipping1993 595].

Within the last year, three papers have been published from a project titled ‘Supply and Demand in Neolithic Europe’, which makes further use of the NEOMINE radiocarbon dates. The first of these supports the previous assertion that itinerant European Neolithic groups were mining for axe materials because these tools were needed to clear the land for farming. The aforementioned period of intensive axe production and forest clearing prior to farming appears to be unique to Britain as northwest Europe does not show similar behaviour [@schauer2019a p157]. It is suggested that demand for axes here may instead be a response to the appearance of imported Alpine Jade axes of high symbolic or status significance [@schauer2019a p158]. Since Pitts’ paper in which he devised new, broader stone groups, geochemical analyses have actually helped to assert that the original IPC groupings are useful after all, representing actual groups of axes with homogenous provenance [@schauer2019b 2]. Spatial analysis of Neolithic axehead findspots has recently indicated that the majority of similar stone axe heads tend to be found near to their original source, however axes made from certain types of stone appear to be found further afield than others [@schauer2019b 15, 20]. Perhaps this could be due to the strength of the raw material, which could either indicate preference or simply less likelihood of breakage in transit. Finally, 39 new results from two different radiocarbon calibration methods, using radiocarbon dates from the NEOMINE project, indicate that almost all of the quarries and mines, in both north and south England, were active contemporaneously [@edinborough2020 27]. This then suggests that differing shape or size is not necessarily a product of change over time. The fact that the start dates of these mines are all very similar also shows the sheer scale and sudden onset of the demand for these axes [@edinborough2020 27]. It has also been suggested that the immigrant Neolithic populations were from Brittany, as populations there had already began to manufacture high-quality axes similar to those made of jade from the Alps. In light of these recent findings, it appears as though all Neolithic axes from Britain – not imported – were mostly used for chopping trees. 

## Methodological context in archaeology

### Data extraction methods

For text and data extraction of archaeological data from handwritten documents there appear to be two routes which are most pursued. These are transcription or handwriting text recognition (HTR) methods. The former appears to be more popularly used for analog datasets compiled by other archaeologists. Non-digital datasets come with their own problems, such as not being collected with the intention of others using it initially, or not having potential computational methods for extraction and analysis in mind [@faniel2018 106], particularly with legacy datasets. Much archaeological data is still paper-based [@emmitt2019 1], and as computational methods become more prevalent in archaeology, much of this data may need to be digitized. Even if archaeological data has been digitized, sometimes this is in the form of scanned images, for example the dataset in this project, which was scanned in 2016. This is more akin to data back-up. For very large digitization projects, crowdsourcing could be a favourable option, and the MicroPasts crowdsourcing platform has been used for this increasingly within archaeology. Released in 2013 and developed mainly by UCL and The British Museum, one of its first projects involved the transcription of over 30,000 artefact information cards about Bronze Age metal objects [@bonacchi2014 63]. The platform was borne out of concern for the lack of open data in archaeology, coupled with an ambition for fostering institutional and community collaboration. Current transcription projects include one which involves Leonard Woolley’s field notes. Other crowdsourcing platforms include the more well-known Zooniverse, launched in 2007, which is much more general in subject area. HTR is an alternative to transcription, however archaeological applications in recent years tend to be on ancient data. Examples include translating and segmenting Akkadian inscriptions with a recurrent neural network amongst other methods [@gordin2020 8-9].

In terms of extracting data from images prior to morphometric analysis, it appears that most studies have done this manually. This process usually necessitates the creation of a digitized outline and the placing of equally spaced coordinates or landmarks around it. One early example places landmarks around photographs of human phalanxes using a digitizer tablet [@palmqvist1996 105]. A number of studies have used drawings of Bronze Age axes traced from a corpus of images which were scanned [@forel2009 722; @monna2013 510; @wilczek2015 383]. Forel *et al.* extracted coordinates by manually placing the start and end points, however Monna *et al.* used an unprovided MATLAB script, and Wilczek *et al.* do not say how their points were extracted, however they cite Monna *et al.* as an example extraction methodology. Some more recent studies use software called tpsDIG2 to extract landmarks, for example on Middle Palaeolithic bifaces [@iovita2010 243]; on Acheulian handaxes [@iovita2017 10]; and recently again on Acheulian handaxes by staff at the British Museum [@garciamedrano2020 5], however this still appears to be manual, and slightly cumbersome as it deals with one image at a time, each of which needs to be inspected by the user for correctness. A very recent study, which lists a co-creator of `Momocs` as a co-author, uses Photoshop to create outline silhouettes of ancient barley grains and ImageJ to manually place landmarks [@wallace2019 1129]. 

### Morphometric analysis

Morphometric analysis is the statistical treatment of size and shape [@claude2008 1]. Applications of morphometric analysis in archaeology first dealt with size only, taking the form of multivariate analyses on artefact measurements under the name ‘numerical taxonomy’, which first arose in the 1960s. Taking inspiration from its uptake in biology [@doran1975 159], [@shennan1988 192], proponents of this method hoped that it would be a good way of checking if traditional classification was valid or not, and also be useful for analysing large amounts of artefacts [@doran1975 186]. In one of the very earliest instances of this method, numerical taxonomy is introduced as an objective method of study, proposed for use in grouping British lower and upper Palaeolithic handaxes [@roe1969 23]. Other proponents of the method used this paper as a case study for how it should be carried out [@hodson1971 37]. With this adoption came a number of publications also voicing concern that numerical typology may be reinforcing the bad aspects of archaeological classification, for example forcing the existence of predetermined types [@thomas1972 39], and that results were validated on whether or not they fitted these types [@shennan1988 193, 194]. This is also the method used in Pitts’ 1996 paper on the axe measurements from his compiled dataset. In recent years it appears that this method has fallen out of favour in archaeology.

Similarly to numerical taxonomy, archaeologists later took influence again from biology, or biometrics, but began to consider shape rather than size. These more complex morphometric methods do not appear to arise in archaeology until the mid 1990s [@wilczek2015 382]. One such example is that of a study on Acheulian handaxes from Israel, where landmarks were placed on outlines of the axes where measurements were taken manually, and then the landmark positions were compared between the axes. This was done by using Hotelling’s t^2^ to test for statistically significant differences in mean landmark position on outlines drawn in two-dimensional cartesian space from their measurements [@brande1996 425].  Another contemporary study used elliptical fourier analysis on a human phalanx to compare it to gorilla, Old World monkey, and other human phalanxes [@palmqvist1996 99]. In recent years, morphometric analyses in archaeology have increasingly focused on comparing axe shapes from certain periods. One early example is Forel et al., who use discrete cosine transform, a Fourier-related method on lateral ribs of bronze age axes in the form of line drawings, implemented with MATLAB [@forel2009 723].  Another study from around the same time examined and compared resharpened stone tools at different stages in their use-lives using elliptical Fourier analysis (Ioviţă 2010, p243). In the last decade, the `Momocs` R package for shape morphometrics has been increasingly used in archaeology. The impetus behind Momocs was to create one package for outline morphometric analysis in R, which as yet had not existed, and contemporaneous morphometry-adjacent packages focused primarily on placing landmarks [@bonhomme2014 4]. Wilczek et al. use Momocs alongside a vast number of other methods to reveal groups in Bronze Age flanged axes [@wilczek2015 385]. A 2017 paper uses elliptical Fourier analysis with Momocs to investigate whether Acheulian handaxes became more symmetrical in design as time progressed [@iovita2017 10]. Something that is apparent in the literature is that many morphometric analyses tend to focus on either shape or size but not both, perhaps with the exception of @brande1996.

### Reproducibility

Something many of the studies mentioned in this methodological background have in common is that their computational analyses or data extraction methods are not reproducible. This is true even for the more recent publications mentioned, for example those using Momocs, a package made to facilitate reproducibility in morphometric analyses, as they manually extracted points from the outlines before importing. The sharing and citation of data, as well as the sharing of reproducible methods used to arrive at published results, is still relatively rare in archaeology [@lodwick2019 14]. Materials and methods sections of archaeological research papers can often be vague, sometimes not even citing all software used. Not only does this damage the credibility of published results as colleagues are unable to ascertain whether these methods actually do work, it also means that the methods cannot be improved upon or utilized by others, or perhaps even used again by their authors [@marwick2017 425]. Even if methods are shared fully, often archaeologists are using proprietary software such as SPSS or MATLAB [@marwick2017 431], which either uses point-and-click methods or is behind a paywall. Furthermore, it prevents collaboration with experts from other fields as they are unable to share workflows. Meanwhile, discussions around open data are becoming more common in archaeology, particularly in archaeozoology [@kansa13 90] and in archaeobotany [@lodwick2019 14]. There is also MicroPasts, which hosts publicly available crowdsourced datasets, and the new *Journal of Open Archaeology Data*, which publishes descriptions of datasets and information on how to access them.

\clearpage