```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```


```{r include_packages_2, include = FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis and also two functions
# used for labeling and referencing
library(tidyverse)
library(ggplot2)
library(ggmap)
library(factoextra)
library(ggfortify)
library(knitr)
library(kableExtra)
library(patchwork)
```


```{r}
my_theme <-
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        strip.background = element_blank(),
        axis.line = element_blank())
```


```{r data, echo=FALSE, message=FALSE}
neo_axes <- read_csv("data/micropasts-neoaxes1.csv", 
                     col_types = cols(.default = col_character()))

neo_axes_long <- neo_axes %>%
  pivot_longer(areablad:weight, 
               names_to = "feature",
               values_to = "measurement") %>%
  filter(!is.na(measurement)) %>%
  mutate(across("measurement", as.numeric))
```

# Exploratory data analysis with Micropasts data

## Sorting varariables

```{r features-dotplot, echo=FALSE, messsage=FALSE}
neo_axes_long %>%
  group_by(feature) %>%
  mutate(n = n()) %>%
  # filter(n > 50) %>%
  ungroup() %>%
  mutate(feature = fct_reorder(feature, n, .desc = FALSE),
         id = fct_reorder(as.character(axe_id), n)) %>%
  ggplot(aes(colour = condition)) +
  geom_point(aes(x = id, y = feature)) +
  theme(axis.text.x = element_blank())
        # axis.text.x = element_text(angle = 90, vjust = 0.5),
        #legend.position = c(.8, .4)) +
  my_theme
```



```{r sorting, echo=FALSE, message=FALSE}
feature_n <- neo_axes_long %>%
  group_by(feature, condition) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  group_by(condition) %>%
  mutate(n_scaled = n / max(n)) %>%
  arrange(desc(n))

most_common_features <- feature_n %>%
  filter(n > 385)

neo_axes_long_mcf <- neo_axes_long %>%
  semi_join(most_common_features, by = "feature") %>%
  filter(condition == "complete")
```

\clearpage

<!-- clearpage ends the page, and also dumps out all floats.
  Floats are things like tables and figures. -->

##Univariate

```{r density-plots, message=FALSE, echo=FALSE, fig.height=10, fig.cap="Density plots"}
msrmnt_means <- neo_axes_long_mcf %>%
  group_by(feature) %>%
  summarise(mean.mm = mean(measurement, na.rm = TRUE))

msrmnt_meds <- neo_axes_long_mcf %>%
  group_by(feature) %>%
  summarise(med.mm = median(measurement, na.rm = TRUE))

neo_axes_long_mcf %>%
  ggplot(aes(x = measurement)) +
  geom_density() +
  geom_vline(data = msrmnt_means, mapping = aes(xintercept = mean.mm),
             color = "red",
             linetype = "dashed") +
  geom_vline(data = msrmnt_meds, mapping = aes(xintercept = med.mm),
             color = "blue",
             linetype = "dashed") +
  geom_rug(alpha = 0.5) +
  facet_wrap(~ feature, scales = "free") +
  my_theme +
  theme(legend.position = "none") +
  expand_limits(x = 0, y = 0)
```


```{r boxplots, echo=FALSE, message=FALSE, fig.height=10, fig.cap="Boxplots"}
neo_axes_long_mcf %>%
  ggplot(aes(x = feature, y = measurement)) +
  geom_boxplot() + 
  # geom_histogram(binwidth = 1, origin = 0) +
  facet_wrap(~ feature, scales = "free") +
  my_theme +
  theme(legend.position = "none", strip.text = element_blank())
```

```{r summary-stats, message=FALSE, echo=FALSE}
neo_axes_long_mcf2 <- neo_axes_long_mcf %>% 
  filter(!(feature %in% c("corfroby", "corbapl", "corfropl", "corbaby")))

neo_axes_wide <- neo_axes_long_mcf2 %>%
  pivot_wider(id = "axe_id", 
              names_from = "feature",
              values_from = "measurement") %>%
  column_to_rownames(var = "axe_id")

kable(summary(neo_axes_wide), caption = "Summary statistics", booktabs = TRUE)

summary(neo_axes_wide)
```


\clearpage 

##Cluster analysis

```{r wss-silhouette, echo=FALSE, message=FALSE, fig.height=4, fig.cap="WSS and average silhouette plots"}
scaled_neo_axes <- neo_axes_wide %>%
  drop_na() %>%
  scale()

p1 <- fviz_nbclust(scaled_neo_axes, kmeans, method = "wss") +
  my_theme
p2 <- fviz_nbclust(scaled_neo_axes, kmeans, method = "silhouette") +
  my_theme

p1 + p2
```


```{r k-means, echo=FALSE, message=FALSE, fig.height=10, fig.cap="K-means clusters"}
kclust2 <- kmeans(scaled_neo_axes, centers = 2, nstart = 50, algorithm = "Hartigan-Wong")
kclust4 <- kmeans(scaled_neo_axes, centers = 4, nstart = 50, algorithm = "Hartigan-Wong")
kclust6 <- kmeans(scaled_neo_axes, centers = 6, nstart = 50, algorithm = "Hartigan-Wong")

kclust3_lookup <- kclust3$cluster %>%
  enframe() %>%
  rename(axe_id = name, cluster = value) %>%
  mutate_at("cluster", ~ as_factor(as.character(.)))

k2 <- fviz_cluster(kclust2, data = scaled_neo_axes) +
  my_theme
k4 <- fviz_cluster(kclust4, data = scaled_neo_axes) +
  my_theme
k6 <- fviz_cluster(kclust6, data = scaled_neo_axes) +
  my_theme

k2 /
k4 /
k6
```

## Within-cluster densities

```{r cluster-densities}
neo_axes_long_mcf2 %>%
  right_join(kclust3_lookup, by = "axe_id") %>%
  ggplot(aes(x = measurement)) +
  geom_density(aes(colour = cluster, fill = cluster), alpha = 0.3) +
  # geom_density(alpha = 0.2) +
  # geom_rug(alpha = 0.5) +
  facet_wrap(~ feature, scales = "free") +
  my_theme +
  theme(legend.position = "right")
```

\clearpage

##Principal components analysis

```{r screeplots, fig.height = 4, fig.cap = "Screeplots of eigenvalues and percentage variance explained"}

neo_axes_PCA <- drop_na(neo_axes_wide) %>%
  prcomp(center = TRUE, scale = TRUE)

sc1 <- fviz_screeplot(neo_axes_PCA, addlabels = TRUE, choice = "eigenvalue") +
  my_theme
sc2 <- fviz_screeplot(neo_axes_PCA, addlabels = TRUE, choice = "variance") +
  my_theme

sc1 + sc2

```


```{r variable-loadings}

map_dfc(1:19, ~neo_axes_PCA$rotation[, .] * sqrt(neo_axes_PCA$sdev ^ 2)[.])

kable(map_dfc(1:19, ~neo_axes_PCA$rotation[, .] * sqrt(neo_axes_PCA$sdev ^ 2)[.]), caption = "Variable loadings", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```



```{r pc1-pc2, fig.height = 5, fig.cap = "PCA: individuals and variables for PC1 and PC2"}

pc1 <- autoplot(neo_axes_PCA, x = 1, y = 2, variance_percentage = TRUE, label = TRUE, label.repel = TRUE, label.size = 1) + my_theme
pc2 <- autoplot(neo_axes_PCA, x = 1, y = 2, variance_percentage = TRUE, colour = 'grey', loadings.label = TRUE, loadings.colour = 'blue', loadings.label.colour = 'blue', loadings.label.repel = TRUE) + my_theme

pc1 /
pc2

```



```{r pc3-pc4, fig.height = 6, fig.cap = "PCA: individuals and variables for PC2 and PC3"}

pc3 <- autoplot(neo_axes_PCA, x = 3, y = 4, variance_percentage = TRUE, label = TRUE, label.repel = TRUE, label.size = 2) +
  my_theme
pc4 <- autoplot(neo_axes_PCA, x = 3, y = 4, variance_percentage = TRUE, colour = 'grey', loadings.label = TRUE, loadings.colour = 'blue', loadings.label.colour = 'blue', loadings.label.repel = TRUE) + my_theme

pc3 /
pc4

```

## Clusters on PCA

```{r pca-cluster, fig.height = 4, fig.cap = "Clusters colour-coded onto plots of the two pairs of axes"}
pcl1 <- autoplot(neo_axes_PCA, data = kclust3, x = 1, y = 2, variance_percentage = TRUE, colour = 'cluster') + my_theme
pcl2 <- autoplot(neo_axes_PCA, data = kclust3, x = 3, y = 4, variance_percentage = TRUE, colour = 'cluster') + my_theme

pcl1 /
pcl2
```

