# Conclusion {-}

Successfully extracting and analysing the data from 1825 record sheets and 1137 technical drawings has not only provided further insight into Neolithic production and trade, but also highlighted the potential contribution to research that digitising legacy data can make. Automating the production of binary masks for use with morphometric packages has demonstrated that this too can be made reproducible, in addition to the analysis itself, which removes the subjective aspect of placing landmarks. In addition, with some improvements, there is the possibility that this method could be used on other analog datasets of drawings or photographs, whether black and white or in colour. The outline analysis of the processed drawings revealed that there are reasonably distinct groups of shapes within this sample of Neolithic axes from Britain, and this could give useful insight for future research. Taken alongside their stone groups, these broad shape categories could be used to determine whether similar shapes originate from certain industrial areas. Crowdsourcing transcriptions of the record sheets called attention to the difficulties which can arise if initial data collection is not carried out with potential future users or analyses in mind. If archaeology is pursuing a philosophy of open data, then rigorous and logical data collection strategies must be made mainstream. Further to this, trialing PCA with a smaller, non-imputed version of the record sheet dataset with no NAs revealed the potential patterns which could emerge had the entire dataset been complete. The vast amount of missing measurements from the wider dataset most likely contributed to the inconclusive results. Comparing the two analyses showed some correlation between narrow shapes and small measurements, however was largely inconclusive due to missing data. The lack of similarity between axes found near to one another further supports recent research which suggests that axes often traveled far from their sources, and probably changed hands more than once.

The reproducible workflow of this project has utilised tools such as GNU Make and Docker which are typically used for building software, in order to not only make the analyses reproducible, but also the data extraction and cleaning, and to facilitate the use of large swathes of packages without compromising reproducibility. The author hopes to see similar reproducible strategies being utilized within archaeology in the coming decades. This is especially pertinent given that most articles consulted in the methodological literature review, bar the few which were solely about reproducibility, were not only not reproducible but also difficult to establish a workflow for. This became especially evident when attempting to find example workflows for `Momocs`, as many methodologies included manual steps or simply did not explain certain methods. It thus becomes difficult to learn from others who have published. 

A possible future direction for the automated mask processing method would be to improve it so that common issues are mitigated against, for example by increasing the size of the bounding box used to crop the images. Since `Momocs` was so useful in revealing shapes within the axe drawing dataset, this reproducible methodology could be used to extract data for other artefact images, and it would be good to develop this method for transferability. This is especially useful in light of the recent newly released version 2 of `Momocs`, now part of `MomX`, which may result in the uptake of more morphometric analyses in the coming years, hopefully in archaeology. In addition to this, because the volunteers on MicroPasts mostly adhered to the instructions and transcribed that was written in the record sheets, this dataset could be used for HTR training labels and data in future, and this is partly why the instructions were written this way. The transcribed record sheet data is now publicly available for download in JSON files from the MicroPasts website, however the author plans to make available the enclosed cleaned CSV version in the coming months.